Repository Mallang-Trip/Web, pull requests merged in 2024-06, with the labels that each got.

#99 QA 마지막 말랑레디에 대한 체크모달 추가 및 이용약관 내용 수정
  src/pages/PartyPage/MallangReady/index.jsx
  src/pages/PolicyPage/DriverService/index.jsx
Labels: ✨ Feature, 📃 Docs

#101 각종 리팩토링 & 스타일 수정
  .github/workflows/deploy.yml
  index.html
  public/firebase-messaging-sw.js
  public/sw.js
  src/App.jsx
  src/api/image.js
  src/components/Comment/AddComment/index.jsx
  src/components/EditButton/index.jsx
  src/components/ImageBox/ImageModal/index.jsx
  src/components/PartyIconBox/ShareModal/index.jsx
  src/components/PartyPlan/index.jsx
  src/components/PlaceMap/DestinationModal/ShareModal/index.jsx
  src/components/PlaceMap/NewPlaceModal/PlaceFormModal/ImageInput/index.jsx
  src/components/PushNotification/index.jsx
  src/config/properties.js
  src/global/index.js
  src/hooks/useInitialSetting.jsx
  src/pages/AdminPage/Management/Place/DestinationModal/EditPlaceModal/ImageInput/index.jsx
  src/pages/AdminPage/Management/Place/DestinationModal/ShareModal/index.jsx
  src/pages/AdminPage/Management/Place/NewPlaceModal/PlaceFormModal/ImageInput/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/EditFormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/NewRegion/FormModal/index.jsx
  src/pages/AdminPage/Payment/ReceiptModal/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverDetail/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/ProfileImage/index.jsx
  src/pages/CommunityPage/ArticleDetail/ArticleBody/ShareModal/index.jsx
  src/pages/CommunityPostPage/ArticleInfoForm/ImageInputBox/ImageInput/index.jsx
  src/pages/DriverApplyPage/CarInfo/index.jsx
  src/pages/DriverApplyPage/DriverDocument/index.jsx
  src/pages/DriverCoursePage/CourseImage/ImageInput/index.jsx
  src/pages/DriverProfilePage/IconBox/ShareModal/index.jsx
  src/pages/MyProfilePage/DriverProfile/index.jsx
  src/pages/MyProfilePage/UserProfile/index.jsx
  src/pages/PartyHistoryPage/PartyItem/index.jsx
  src/pages/SignupPage/Profile/index.jsx
  src/pages/SignupPage/index.jsx
  src/pages/TalkPage/TalkRoom/ImageModal/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/MenuMembers/InviteModal/SearchMemberList/Member/index.jsx
  src/pages/TalkPage/TalkRoom/index.jsx
  src/pages/TalkPage/index.jsx
  src/utils/axios.js
  src/utils/data.js
Labels: 🔨 Refactor, ⚙ Setting

#104 Fix/enable choice for duplicated place
  src/components/PlaceMap/DestinationModal/index.jsx
  src/pages/DriverCoursePage/CourseDnD/index.jsx
  src/pages/PartyPage/CourseDnD/index.jsx
Labels: ✨ Feature
