Repository Mallang-Trip/Web, pull requests merged in 2024-09, with the labels that each got.

#215 feat: 관리자 페이지 > 드라이버 정보 내 차량 이미지 확대하여 볼 수 있도록 수정
  src/pages/MyProfilePage/DriverProfile/Vehicle/VehicleImage/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx
Labels: ✨ Feature

#218 feat: 회원 수 기능 추가 및 코드 리팩토링
  src/pages/AdminPage/KPI/Container/index.jsx
  src/pages/AdminPage/KPI/index.jsx
Labels: ✨ Feature, 🔨 Refactor

#219 feat: 프로모션 코드
  src/pages/NewPartyPage/Atom/CreateModal/index.jsx
  src/pages/NewPartyPage/Promotion/index.tsx
  src/pages/NewPartyPage/Reservation/index.jsx
Labels: ✨ Feature, 🔨 Refactor

#222 프로모션 코드 가격 체크
  src/pages/NewPartyPage/Promotion/index.tsx
  src/pages/NewPartyPage/Reservation/index.jsx
Labels: ✨ Feature

#223 프로모션 코드 사용시 결제 수단 등록 패스
  src/pages/NewPartyPage/Reservation/index.jsx
Labels: ✨ Feature

#224 새로운 파티 코스 변경 프로모션 적용 가능
  src/pages/NewPartyPage/Edit/index.jsx
Labels: ✨ Feature

#228 feat: 기존 파티에서도 프로모션 코드 추가 및 가입 신청 시 request body 추가
  src/components/Promotion/index.tsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/Reservation/index.jsx
  src/pages/PartyPage/EditModal/index.jsx
  src/pages/PartyPage/JoinModal/index.jsx
  src/pages/PartyPage/index.jsx
Labels: ✨ Feature

#229 기존 파티에서도 프로모션 코드 사용 가능
  src/components/Promotion/index.tsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/Reservation/index.jsx
  src/pages/PartyPage/EditModal/index.jsx
  src/pages/PartyPage/JoinModal/index.jsx
  src/pages/PartyPage/index.jsx
Labels: ✨ Feature

#230 feat: 랜딩페이지 내 프로모션 배너 추가
  src/assets/images/프로모션코드 배너-04.png
  src/pages/LandingPage/NewMyParty/index.jsx
  src/pages/LandingPage/index.jsx
Labels: ✨ Feature, 🎨 Style

#231 랜딩페이지 내 프로모션 배너 추가
  src/assets/images/프로모션코드 배너-04.png
  src/pages/LandingPage/NewMyParty/index.jsx
  src/pages/LandingPage/index.jsx
Labels: ✨ Feature

#220 fix: 커뮤니티 내 하트(좋아요) 제거
  src/pages/CommunityPage/ArticleDetail/ArticleBody/index.jsx
Labels: ✨ Feature
