Repository Mallang-Trip/Web, pull requests merged in 2024-08, with the labels that each got.

#186 PASS 본인 인증 적용
  index.html
  src/api/users.js
  src/assets/images/PASS-Logo.png
  src/assets/svg/Pass-Mobile-Arrow.svg
  src/assets/svg/masking_identity_number.svg
  src/components/PWAInstall/index.jsx
  src/components/PassCheck/index.jsx
  src/components/Title/index.jsx
  src/pages/SignupPage/PersonalInfo/CompleteModal/index.jsx
  src/pages/SignupPage/PersonalInfo/TelecomModal/index.jsx
  src/pages/SignupPage/PersonalInfo/index.jsx
  src/pages/SignupPage/index.jsx
Labels: ✨ Feature, 📬 API

#185 스크롤바 디자인 적용
  src/components/CourseList/index.jsx
  src/components/DriverInfo/index.jsx
  src/components/PlaceMap/DestinationModal/index.jsx
  src/components/PlaceMap/NewPlaceModal/PlaceFormModal/index.jsx
  src/components/PlaceMap/NewPlaceModal/index.jsx
  src/components/ReportModal/index.jsx
  src/index.css
  src/pages/AdminPage/CustomerService/Help/EditForm/index.jsx
  src/pages/AdminPage/CustomerService/Report/ReportContent/MallangTalkModal/index.jsx
  src/pages/AdminPage/Management/Place/DestinationModal/EditPlaceModal/index.jsx
  src/pages/AdminPage/Management/Place/DestinationModal/index.jsx
  src/pages/AdminPage/Management/Place/NewPlaceModal/PlaceFormModal/index.jsx
  src/pages/AdminPage/Management/Place/NewPlaceModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/EditFormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/NewRegion/FormModal/index.jsx
  src/pages/AdminPage/Payment/MallangTalkModal/index.jsx
  src/pages/AdminPage/Payment/ReceiptModal/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
  src/pages/AdminPage/User/UserInfo/UserTable/RegionModal/index.jsx
  src/pages/CommunityPage/Tab/index.jsx
  src/pages/CommunityPostPage/ArticleBodyForm/index.jsx
  src/pages/CommunityPostPage/ArticleInfoForm/PartySelectBox/PartyModal/HeartList/index.jsx
  src/pages/CommunityPostPage/ArticleInfoForm/PartySelectBox/PartyModal/ReservationList/index.jsx
  src/pages/DriverApplyPage/CarInfo/index.jsx
  src/pages/DriverCoursePage/CourseImage/index.jsx
  src/pages/DriverCoursePage/PriceList/index.jsx
  src/pages/DriverProfilePage/CarInfo/index.jsx
  src/pages/LandingPage/PartyFilter/RegionModal/index.jsx
  src/pages/MyProfilePage/DriverProfile/BasicInfo/RegionModal/index.jsx
  src/pages/MyProfilePage/DriverProfile/Price/PriceModal/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/ImageInput/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/VehicleImage/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx
  src/pages/PartyPage/JoinGreeting/index.jsx
  src/pages/PartyPage/PartyMember/index.jsx
  src/pages/TalkPage/TalkList/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/MenuMembers/InviteModal/SearchMemberList/Member/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/MenuMembers/InviteModal/SearchMemberList/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/MenuMembers/index.jsx
  src/pages/TalkPage/TalkRoom/TalkRoomBody/index.jsx
Labels: 🎨 Style

#183 feat : 프로필 클릭시 프로필 오버레이 적용
  src/pages/CommunityPage/ArticleDetail/ArticleBody/index.jsx
Labels: ✨ Feature, 🎨 Style

#188 Google Tag Manager 적용
  .github/workflows/deploy_production.yml
  package-lock.json
  package.json
  src/App.jsx
  src/hooks/useGoogleTagManager.jsx
Labels: 🌏 Deploy, ⚙ Setting

#189 말랑챗 채팅방 리스트 스타일 수정
  src/components/ReportModal/index.jsx
  src/pages/TalkPage/TalkList/TalkItem/index.jsx
Labels: 🎨 Style

#190 말랑챗 탈퇴 오류 & 댓글 삭제 확인
  src/components/Comment/CommentList/Comment/index.jsx
  src/components/Comment/CommentList/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/ExitButton/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/MenuMembers/Member/index.jsx
Labels: ✨ Feature

#191 말랑챗 푸시 알림 사용성 개선
  public/firebase-messaging-sw.js
Labels: ✨ Feature, ⚙ Setting

#192 푸시 알림 UX 개선
  index.html
  public/firebase-messaging-sw.js
Labels: ✨ Feature

#194 style : comment radius 깨짐 해결
  src/pages/PartyPage/JoinGreeting/index.jsx
Labels: 🎨 Style

#196 말랑챗 디테일 기능 추가
  src/pages/TalkPage/TalkRoom/TalkMenu/MenuMembers/Member/index.jsx
  src/pages/TalkPage/TalkRoom/TalkRoomForm/index.jsx
  src/pages/TalkPage/TalkRoom/index.jsx
Labels: ✨ Feature

#197 말랑챗 기능 오류 수정
  src/components/ProfileModal/ButtonBox/ButtonList/BlockModal/index.jsx
  src/pages/PartyPage/JoinGreeting/index.jsx
  src/pages/TalkPage/TalkList/NewTalkButton/NewTalkModal/index.jsx
  src/pages/TalkPage/TalkRoom/ImageModal/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/MenuMembers/Member/index.jsx
  src/pages/TalkPage/TalkRoom/TalkRoomForm/index.jsx
  src/pages/TalkPage/TalkRoom/index.jsx
Labels: 🐛 Bug

#198 새로운 파티 만들기 로직 수정 & 커뮤니티 게시글 신고
  src/pages/CommunityPage/ArticleDetail/ArticleBody/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PartyDate/index.jsx
  src/pages/NewPartyPage/index.jsx
Labels: ✨ Feature

#199 여행 지역 도 단위 관리 & 결제 재시도 기능 추가
  src/api/card.js
  src/pages/AdminPage/Management/Region/RegionList/EditFormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/NewRegion/FormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/RegionItem/index.jsx
  src/pages/LandingPage/PartyList/PartyBox/index.jsx
  src/pages/LandingPage/PartyList/index.jsx
  src/pages/MyReservationPage/ReservationList/ReservationYear/index.jsx
  src/pages/NewPartyPage/Region/index.jsx
  src/pages/PartyPage/CreditInfo/index.jsx
  src/pages/PartyPage/index.jsx
Labels: 🐛 Bug

#203 디바이스 관련 약관 수정
  src/pages/PolicyPage/DriverService/index.jsx
  src/pages/PolicyPage/UserService/index.jsx
  src/utils/firebase.js
Labels: 🌏 Deploy

#204 fix: 가고 싶은 여행지 목록 중 '그 외' 최하단으로 sort
  src/pages/NewPartyPage/Region/index.jsx
Labels: 🔨 Refactor

#207 어드민 페이지 가고싶은 지역 탭 추가/편집 모달창에서 도 지역 삭제
  src/pages/AdminPage/Management/Region/RegionList/EditFormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/NewRegion/FormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/RegionItem/index.jsx
Labels: ✨ Feature

#208 관리자 가고 싶은 지역 관리 도 지역 삭제
  src/pages/AdminPage/Management/Region/RegionList/EditFormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/NewRegion/FormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/RegionItem/index.jsx
Labels: ✨ Feature

#212 feat : 결제 수단 등록 완료시 모달창 기능 추가
  src/components/Credit/index.jsx
Labels: ✨ Feature

#213 feat: 평점 기능 추가, 결제 수단 등록 완료시 완료 모달 추가 및 AddComment 컴포넌트 타입스크립트로 마이그레이션 진행
  .eslintignore
  .eslintrc.cjs
  src/assets/svg/emptyStar.svg
  src/assets/svg/halfStar.svg
  src/assets/svg/rateFillStar.svg
  src/assets/svg/star.svg
  src/components/Comment/AddComment/StarInput/index.tsx
  src/components/Comment/AddComment/index.tsx
  src/components/Credit/index.jsx
  src/custom.d.ts
  src/redux/store.ts
  tsconfig.json
Labels: ✨ Feature, 🔨 Refactor
