Repository Mallang-Trip/Web, pull requests merged in 2024-05, with the labels that each got.

#85 새로운 기획 요구 사항 반영
  src/assets/svg/kakao-icon.svg
  src/assets/svg/new-party-icon.svg
  src/pages/DriverApplyPage/Agreement/AgreeItem/index.jsx
  src/pages/DriverApplyPage/Agreement/index.jsx
  src/pages/DriverApplyPage/CarInfo/index.jsx
  src/pages/DriverApplyPage/Complete/CancelModal/index.jsx
  src/pages/DriverApplyPage/DriverDocument/index.jsx
  src/pages/DriverApplyPage/StepButton/index.jsx
  src/pages/DriverApplyPage/Stepper/index.jsx
  src/pages/DriverApplyPage/Title/index.jsx
  src/pages/DriverApplyPage/index.jsx
  src/pages/LandingPage/KakaoButton/index.jsx
  src/pages/LandingPage/NewPartyButton/index.jsx
Labels: ✨ Feature, 🎨 Style

#87 관리자 신고 내역 관리
  src/api/admin.js
  src/assets/svg/report-vector.svg
  src/components/Admin/ProfileModal/ButtonBox/ButtonList/BlockModal/index.jsx
  src/components/Admin/ProfileModal/ButtonBox/ButtonList/Button/index.jsx
  src/components/Admin/ProfileModal/ButtonBox/ButtonList/index.jsx
  src/components/Admin/ProfileModal/ButtonBox/MyProfileButton/index.jsx
  src/components/Admin/ProfileModal/ButtonBox/index.jsx
  src/components/Admin/ProfileModal/ModalCloser/index.jsx
  src/components/Admin/ProfileModal/ProfileInfo/index.jsx
  src/components/Admin/ProfileModal/index.jsx
  src/components/Admin/SuspensionModal/index.jsx
  src/components/ProfileModal/ButtonBox/AdminButtonList/ConfirmModal/index.jsx
  src/components/ProfileModal/ButtonBox/AdminButtonList/SuspensionModal/index.jsx
  src/components/ProfileModal/ButtonBox/AdminButtonList/index.jsx
  src/components/ProfileModal/ButtonBox/ButtonList/Button/index.jsx
  src/components/ProfileModal/ButtonBox/index.jsx
  src/components/ProfileModal/ProfileInfo/index.jsx
  src/components/ProfileModal/index.jsx
  src/components/TabList/index.jsx
  src/pages/AdminPage/CustomerService/Report/ReportContent/MallangTalkModal/index.jsx
  src/pages/AdminPage/CustomerService/Report/ReportContent/index.jsx
  src/pages/AdminPage/CustomerService/Report/Tab/index.jsx
  src/pages/AdminPage/CustomerService/Report/TableBody/ReportItem/index.jsx
  src/pages/AdminPage/CustomerService/Report/TableBody/index.jsx
  src/pages/AdminPage/CustomerService/Report/TableHead/index.jsx
  src/pages/AdminPage/CustomerService/Report/index.jsx
  src/pages/AdminPage/Notification/Noti/index.jsx
  src/pages/AdminPage/Payment/index.jsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#88 유저 정지 해제 로직 및 API 수정
  src/api/admin.js
  src/components/ProfileModal/ButtonBox/AdminButtonList/index.jsx
  src/pages/AdminPage/CustomerService/Report/ReportContent/index.jsx
  src/pages/AdminPage/CustomerService/Report/index.jsx
Labels: ✨ Feature, 📬 API

#90 변경된 기획 요구 사항 반영
  src/components/CourseMap/index.jsx
  src/components/PlaceMap/DestinationModal/index.jsx
  src/components/PlaceMap/MapBox/index.jsx
  src/components/PlaceMap/NewPlaceModal/index.jsx
  src/components/ProfileModal/ProfileInfo/index.jsx
  src/components/ProfileModal/index.jsx
  src/pages/AdminPage/Management/Place/DestinationModal/index.jsx
  src/pages/AdminPage/Management/Place/NewPlaceModal/index.jsx
  src/pages/AdminPage/Management/Place/PlaceMap/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverTable/Body/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverTable/Head/index.jsx
  src/pages/DestinationPage/PlaceInfoBox/PlaceInfoTitle/index.jsx
  src/pages/DriverApplyPage/Accout/index.jsx
  src/pages/DriverApplyPage/RegionList/Region/index.jsx
  src/pages/DriverApplyPage/index.jsx
  src/pages/DriverCoursePage/index.jsx
  src/pages/MyProfilePage/DriverProfile/Price/PriceModal/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/Reservation/index.jsx
  src/pages/PartyPage/PartyMember/index.jsx
  src/pages/PartyPage/index.jsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#92 파티 관련 수정 사항 반영
  src/components/CourseMap/index.jsx
  src/pages/LandingPage/KakaoButton/index.jsx
  src/pages/LandingPage/NewPartyButton/index.jsx
  src/pages/NewPartyPage/index.jsx
  src/pages/PartyPage/JoinButton/index.jsx
  src/pages/PartyPage/PartyMember/index.jsx
  src/pages/PartyPage/index.jsx
  src/utils/data.js
Labels: ✨ Feature, 🐛 Bug, 🔨 Refactor

#93 나의 결제/환불 내역
  src/api/card.js
  src/components/Header/index.jsx
  src/pages/MyMenuPage/Menu/index.jsx
  src/pages/MyPaymentListPage/PaymentTable/Body/index.jsx
  src/pages/MyPaymentListPage/PaymentTable/Head/index.jsx
  src/pages/MyPaymentListPage/PaymentTable/index.jsx
  src/pages/MyPaymentListPage/index.jsx
  src/pages/MyReservationPage/ReservationList/ReservationYear/index.jsx
  src/router/index.jsx
Labels: ✨ Feature, 📬 API

#95 QA 수정사항 반영
  src/api/notification.js
  src/components/PlaceMap/SearchBox/index.jsx
  src/components/PlaceMap/index.jsx
  src/pages/DriverCoursePage/CourseImage/index.jsx
  src/pages/DriverCoursePage/SaveButton/index.jsx
  src/pages/LandingPage/PartyFilter/RegionModal/index.jsx
  src/pages/LandingPage/PartyFilter/index.jsx
  src/pages/LoginSearchPage/Search/SearchForm/SearchAcount/index.jsx
  src/pages/MyProfilePage/DriverProfile/ProfileHeader/index.jsx
  src/pages/MyProfilePage/DriverProfile/index.jsx
  src/pages/MyProfilePage/UserProfile/LoginInfo/ExitButton/ExitModal/index.jsx
  src/pages/MyProfilePage/UserProfile/ProfileHeader/index.jsx
  src/pages/MyProfilePage/UserProfile/index.jsx
  src/pages/NewPartyPage/Region/RegionButton/index.jsx
  src/pages/NewPartyPage/Region/index.jsx
  src/pages/NotifyPage/NotifyList/index.jsx
Labels: ✨ Feature, 🐛 Bug, 🔨 Refactor

#96 푸시 알림 & QA 수정 사항 반영
  .env
  index.html
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  public/manifest.json
  public/pwa-sw.js
  src/App.jsx
  src/api/notification.js
  src/components/Footer/Policy/index.jsx
  src/components/Loading/index.jsx
  src/components/PlaceMap/SearchBox/index.jsx
  src/components/PlaceMap/index.jsx
  src/components/PushNotification/ConfirmModal/index.jsx
  src/components/PushNotification/index.jsx
  src/pages/DriverCoursePage/CourseImage/index.jsx
  src/pages/DriverCoursePage/SaveButton/index.jsx
  src/pages/LandingPage/PartyFilter/RegionModal/index.jsx
  src/pages/LandingPage/PartyFilter/index.jsx
  src/pages/LoginSearchPage/Search/SearchForm/SearchAcount/index.jsx
  src/pages/MyProfilePage/DriverProfile/ProfileHeader/index.jsx
  src/pages/MyProfilePage/DriverProfile/index.jsx
  src/pages/MyProfilePage/UserProfile/LoginInfo/ExitButton/ExitModal/index.jsx
  src/pages/MyProfilePage/UserProfile/ProfileHeader/index.jsx
  src/pages/MyProfilePage/UserProfile/index.jsx
  src/pages/NewPartyPage/Region/RegionButton/index.jsx
  src/pages/NewPartyPage/Region/index.jsx
  src/pages/NotifyPage/NotifyList/index.jsx
  src/redux/modules/userSlice.js
  src/utils/firebase.js
  sw.js
Labels: ✨ Feature, 🎨 Style, 📬 API, 🔨 Refactor

#97 관리자 피드백 & 권한 부여 & 약관 메일 알림 UI
  src/pages/AdminPage/Management/Feedback/FeedbackItem/index.jsx
  src/pages/AdminPage/Management/Feedback/Tab/index.jsx
  src/pages/AdminPage/Management/Feedback/index.jsx
  src/pages/AdminPage/Notification/Noti-mail/Tab/index.jsx
  src/pages/AdminPage/Notification/Noti-mail/TableBody/NotiMailsItem/index.jsx
  src/pages/AdminPage/Notification/Noti-mail/TableBody/index.jsx
  src/pages/AdminPage/Notification/Noti-mail/TableHead/index.jsx
  src/pages/AdminPage/Notification/Noti-mail/WriteEmail/index.jsx
  src/pages/AdminPage/Notification/Noti-mail/index.jsx
  src/pages/AdminPage/User/AdminAuth/AddUserModal/AdminUserItem/index.jsx
  src/pages/AdminPage/User/AdminAuth/AddUserModal/index.jsx
  src/pages/AdminPage/User/AdminAuth/TableBody/AdminAuthItem/index.jsx
  src/pages/AdminPage/User/AdminAuth/TableBody/index.jsx
  src/pages/AdminPage/User/AdminAuth/TableHead/index.jsx
  src/pages/AdminPage/User/AdminAuth/index.jsx
  src/pages/AdminPage/index.jsx
Labels: ✨ Feature, 🎨 Style
