Repository Mallang-Trip/Web, pull requests merged in 2024-07, with the labels that each got.

#106 feat : 결제 수단 등록 컴포넌트 아래에 잔액 부족시 카드 등록 불가 메세지 추가
  src/components/Credit/index.jsx
Labels: ✨ Feature

#108 fix: 맵 코스 마커 아래 이름 대신 숫자
  src/components/CourseMap/index.jsx
Labels: ✨ Feature, 🎨 Style

#120 feat : 드라이버 차량 사진 여러장 업로드 가능하도록 API 변경점 수정
  package-lock.json
  package.json
  src/pages/AdminPage/User/DriverInfo/DriverDetail/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
  src/pages/DriverApplyPage/CarInfo/index.jsx
  src/pages/DriverApplyPage/index.jsx
  src/pages/DriverProfilePage/CarInfo/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/ImageInput/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/VehicleImage/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx
  src/pages/MyProfilePage/DriverProfile/index.jsx
  src/pages/MyProfilePage/index.jsx
Labels: ✨ Feature, 📬 API

#119 fix: 드라이버가 제안하는 코스 누를 경우 나타나는 페이지 순서 변경
  src/pages/DriverProfilePage/index.jsx
  src/pages/NewPartyPage/Course/index.jsx
  src/pages/NewPartyPage/MemberAndDate/Member/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
Labels: ✨ Feature

#118 여행지 지도 마커 관련 렌더링 최적화
  src/api/region.js
  src/components/PlaceMap/MapBox/index.jsx
  src/components/PlaceMap/SearchBox/index.jsx
  src/components/PlaceMap/index.jsx
  src/pages/AdminPage/Management/Place/PlaceMap/index.jsx
  src/pages/AdminPage/Management/Place/SearchBar/index.jsx
  src/pages/AdminPage/Management/Place/index.jsx
Labels: ✨ Feature, 🔨 Refactor

#122 필수 로그인 페이지 redirect 로직 수정
  src/components/CourseList/CourseItem/index.jsx
  src/components/PWAInstall/index.jsx
  src/hoc/Auth.jsx
  src/pages/DriverProfilePage/CarInfo/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/LoginPage/LoginForm/index.jsx
  src/pages/NewPartyPage/index.jsx
Labels: 🐛 Bug

#123 지도 렌더링 최적화 & redirect 로직 수정 & 드라이버 차량 이미지
  package-lock.json
  package.json
  src/api/region.js
  src/components/BottomNav/index.jsx
  src/components/CourseList/CourseItem/index.jsx
  src/components/PWAInstall/index.jsx
  src/components/PlaceMap/MapBox/index.jsx
  src/components/PlaceMap/SearchBox/index.jsx
  src/components/PlaceMap/index.jsx
  src/hoc/Auth.jsx
  src/pages/AdminPage/Management/Place/PlaceMap/index.jsx
  src/pages/AdminPage/Management/Place/SearchBar/index.jsx
  src/pages/AdminPage/Management/Place/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverDetail/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
  src/pages/DriverApplyPage/CarInfo/index.jsx
  src/pages/DriverApplyPage/index.jsx
  src/pages/DriverProfilePage/CarInfo/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/LoginPage/LoginForm/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/ImageInput/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/VehicleImage/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx
  src/pages/MyProfilePage/DriverProfile/index.jsx
  src/pages/MyProfilePage/index.jsx
  src/pages/NewPartyPage/Course/index.jsx
  src/pages/NewPartyPage/MemberAndDate/Member/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
  src/pages/NewPartyPage/index.jsx
  tailwind.config.js
Labels: 🌏 Deploy

#127 회원가입 나이 제한
  src/pages/SignupPage/PersonalInfo/index.jsx
Labels: ✨ Feature

#128 드라이버 다중 지역 활동
  src/api/region.js
  src/pages/AdminPage/Management/Region/RegionList/EditFormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/NewRegion/FormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/RegionItem/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverCourse/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverTable/Body/index.jsx
  src/pages/AdminPage/User/UserInfo/UserTable/RegionModal/RegionButton/index.jsx
  src/pages/AdminPage/User/UserInfo/UserTable/RegionModal/index.jsx
  src/pages/DriverApplyPage/RegionList/Region/index.jsx
  src/pages/DriverApplyPage/RegionList/index.jsx
  src/pages/DriverApplyPage/index.jsx
  src/pages/DriverCoursePage/CourseImage/index.jsx
  src/pages/DriverCoursePage/index.jsx
  src/pages/DriverProfilePage/ServiceRegion/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/LandingPage/PartyFilter/RegionModal/RegionButton/index.jsx
  src/pages/LandingPage/PartyFilter/RegionModal/index.jsx
  src/pages/MyProfilePage/DriverProfile/BasicInfo/RegionModal/Region/index.jsx
  src/pages/MyProfilePage/DriverProfile/BasicInfo/RegionModal/index.jsx
  src/pages/MyProfilePage/UserProfile/Information/index.jsx
  src/pages/MyProfilePage/index.jsx
  src/pages/NewPartyPage/Atom/CreateModal/index.jsx
  src/pages/NewPartyPage/Atom/TextArea/index.jsx
  src/pages/NewPartyPage/Course/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
  src/pages/NewPartyPage/Region/RegionButton/index.jsx
  src/pages/NewPartyPage/Region/index.jsx
  src/pages/NewPartyPage/Reservation/index.jsx
  src/pages/NewPartyPage/index.jsx
  src/pages/PartyPage/EditMap/index.jsx
  src/pages/PartyPage/EditModal/index.jsx
  src/pages/PartyPage/index.jsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#130 드라이버 여러 지역 활동 & 회원가입 나이 제한
  src/api/region.js
  src/pages/AdminPage/Management/Region/RegionList/EditFormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/NewRegion/FormModal/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/RegionItem/index.jsx
  src/pages/AdminPage/Management/Region/RegionList/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverCourse/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverTable/Body/index.jsx
  src/pages/AdminPage/User/UserInfo/UserTable/RegionModal/RegionButton/index.jsx
  src/pages/AdminPage/User/UserInfo/UserTable/RegionModal/index.jsx
  src/pages/DriverApplyPage/RegionList/Region/index.jsx
  src/pages/DriverApplyPage/RegionList/index.jsx
  src/pages/DriverApplyPage/index.jsx
  src/pages/DriverCoursePage/CourseImage/index.jsx
  src/pages/DriverCoursePage/index.jsx
  src/pages/DriverProfilePage/ServiceRegion/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/LandingPage/PartyFilter/RegionModal/RegionButton/index.jsx
  src/pages/LandingPage/PartyFilter/RegionModal/index.jsx
  src/pages/MyProfilePage/DriverProfile/BasicInfo/RegionModal/Region/index.jsx
  src/pages/MyProfilePage/DriverProfile/BasicInfo/RegionModal/index.jsx
  src/pages/MyProfilePage/UserProfile/Information/index.jsx
  src/pages/MyProfilePage/index.jsx
  src/pages/NewPartyPage/Atom/CreateModal/index.jsx
  src/pages/NewPartyPage/Atom/TextArea/index.jsx
  src/pages/NewPartyPage/Course/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
  src/pages/NewPartyPage/Region/RegionButton/index.jsx
  src/pages/NewPartyPage/Region/index.jsx
  src/pages/NewPartyPage/Reservation/index.jsx
  src/pages/NewPartyPage/index.jsx
  src/pages/PartyPage/EditMap/index.jsx
  src/pages/PartyPage/EditModal/index.jsx
  src/pages/PartyPage/index.jsx
  src/pages/SignupPage/PersonalInfo/index.jsx
Labels: 🌏 Deploy

#131 fix : 드라이버 차량 사진 여러개 업로드
  src/pages/AdminPage/User/DriverInfo/DriverDetail/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverList/DriverItem/index.jsx
  src/pages/DriverApplyPage/CarInfo/CarImage/index.jsx
  src/pages/DriverApplyPage/CarInfo/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/MyProfilePage/DriverProfile/index.jsx
Labels: 🐛 Bug

#133 드라이버 차량 이미지 여러장 등록
  src/pages/AdminPage/User/DriverInfo/DriverDetail/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverList/DriverItem/index.jsx
  src/pages/DriverApplyPage/CarInfo/CarImage/index.jsx
  src/pages/DriverApplyPage/CarInfo/index.jsx
  src/pages/DriverCoursePage/CourseDnD/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/MyProfilePage/DriverProfile/index.jsx
  src/pages/PartyPage/CourseDnD/index.jsx
Labels: 🌏 Deploy

#134 feat: 파티 페이지 파티 소개 항목 추가
  src/pages/PartyPage/PartyIntro/index.jsx
  src/pages/PartyPage/index.jsx
Labels: ✨ Feature

#135 feat : 사진이 없을 때 alt 삭제
  src/pages/MyHeartPage/HeartItem/index.jsx
Labels: ✨ Feature

#140 feat: 코스 수정 시 드라이버가 설정한 시간 별 비용 선택지 추가
  src/pages/NewPartyPage/Atom/CreateModal/index.jsx
  src/pages/NewPartyPage/Edit/PriceList/PriceButton/index.jsx
  src/pages/NewPartyPage/Edit/PriceList/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/Reservation/index.jsx
  src/pages/NewPartyPage/index.jsx
Labels: ✨ Feature, 📬 API

#144 코스 수정시 파티 이름, 출발 시간 변경
  src/pages/DriverCoursePage/CourseDnD/index.jsx
  src/pages/NewPartyPage/Atom/CreateModal/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/PartyPage/CourseDnD/index.jsx
  src/pages/PartyPage/EditModal/index.jsx
  src/pages/PartyPage/index.jsx
Labels: ✨ Feature, 📬 API

#145 드라이버 프로필 관리 & 코스 시간 및 가격 수정
  src/pages/AdminPage/User/DriverInfo/DriverDetail/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverTable/Body/index.jsx
  src/pages/AdminPage/User/DriverInfo/DriverTable/index.jsx
  src/pages/DriverCoursePage/CourseDnD/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/MyProfilePage/DriverProfile/BasicInfo/AccountModal/index.jsx
  src/pages/MyProfilePage/DriverProfile/BasicInfo/index.jsx
  src/pages/MyProfilePage/DriverProfile/License/LicensePicture/index.jsx
  src/pages/MyProfilePage/DriverProfile/License/index.jsx
  src/pages/NewPartyPage/Atom/CreateModal/index.jsx
  src/pages/NewPartyPage/Edit/PriceList/PriceButton/index.jsx
  src/pages/NewPartyPage/Edit/PriceList/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/Reservation/index.jsx
  src/pages/NewPartyPage/index.jsx
  src/pages/PartyPage/CourseDnD/index.jsx
  src/pages/PartyPage/EditModal/index.jsx
  src/pages/PartyPage/index.jsx
Labels: 🌏 Deploy

#147 드라이버 차량 번호 관리
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
  src/pages/DriverApplyPage/CarInfo/index.jsx
  src/pages/DriverApplyPage/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx
Labels: ✨ Feature, 📬 API

#150 fix : 댓글에서 사진 첨부 후 댓글 목록에 사진이 업로드되지 않는 기능 수정
  src/components/Comment/AddComment/index.jsx
  src/components/Comment/CommentList/Comment/CommentImage/index.jsx
  src/components/Comment/CommentList/Comment/index.jsx
Labels: 🐛 Bug

#152 feature : 댓글 작성 시 예외처리
  src/components/Comment/AddComment/index.jsx
  src/components/Comment/CommentList/Comment/index.jsx
Labels: ✨ Feature, 🐛 Bug

#153 드라이버 차량 번호 관리 & 댓글 및 신고 관련 예외 처리
  src/components/Comment/AddComment/index.jsx
  src/components/Comment/CommentList/Comment/CommentImage/index.jsx
  src/components/Comment/CommentList/Comment/index.jsx
  src/components/ProfileModal/ButtonBox/ButtonList/BlockModal/index.jsx
  src/components/ProfileModal/ButtonBox/ButtonList/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
  src/pages/DriverApplyPage/CarInfo/index.jsx
  src/pages/DriverApplyPage/index.jsx
  src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx
  src/pages/NotifyPage/NotifyList/index.jsx
  src/pages/PartyPage/EditModal/index.jsx
  src/pages/PartyPage/JoinModal/index.jsx
Labels: 🌏 Deploy

#156 fix : phoneNumber hypen(-) 삭제
  src/pages/MyProfilePage/DriverProfile/index.jsx
Labels: 🐛 Bug

#159 관리자 여행자 회원 이름 관리
  src/pages/AdminPage/User/UserInfo/UserTable/Body/index.jsx
  src/pages/AdminPage/User/UserInfo/UserTable/Head/index.jsx
Labels: ✨ Feature

#160 관리자 파티 페이지에서 드라이버 이름이 표기 안되는 오류
  src/pages/AdminPage/Management/Party/PartyDetail/index.jsx
  src/pages/AdminPage/User/UserInfo/UserTable/Body/index.jsx
  src/pages/AdminPage/User/UserInfo/UserTable/Head/index.jsx
  src/pages/MyProfilePage/DriverProfile/index.jsx
Labels: 🐛 Bug

#154 fix: 말랑톡 > 말랑챗 이름 수정
  src/components/BottomNav/index.jsx
  src/components/CourseList/index.jsx
  src/components/Footer/Company/index.jsx
  src/components/Header/index.jsx
  src/components/ProfileModal/ButtonBox/AdminButtonList/index.jsx
  src/pages/AdminPage/CustomerService/Report/ReportContent/MallangTalkModal/index.jsx
  src/pages/AdminPage/CustomerService/Report/ReportContent/index.jsx
  src/pages/AdminPage/Payment/Party/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/AcceptButton/index.jsx
  src/pages/CommunityPage/ArticleDetail/ArticleBody/index.jsx
  src/pages/CommunityPage/ArticleDetail/ArticleComment/CommentItem/ReplyItem/index.jsx
  src/pages/CommunityPage/ArticleDetail/ArticleComment/CommentItem/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/IntroPage/ServiceList/index.jsx
  src/pages/NewPartyPage/Course/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
  src/pages/NewPartyPage/Region/index.jsx
  src/pages/NewPartyPage/Reservation/index.jsx
  src/pages/NewPartyPage/index.jsx
  src/pages/TalkPage/TalkList/NewTalkButton/NewTalkModal/NewTalkInfo/index.jsx
  src/pages/TalkPage/TalkList/NewTalkButton/NewTalkModal/index.jsx
  src/pages/TalkPage/TalkList/NoTalkList/index.jsx
  src/pages/TalkPage/TalkList/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/ExitButton/ExitCheckModal/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/ExitButton/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/MenuHead/index.jsx
Labels: ✨ Feature

#161 푸시 알림 권한 로직 수정 & 말랑챗 이름 변경
  src/components/BottomNav/index.jsx
  src/components/CourseList/index.jsx
  src/components/Footer/Company/index.jsx
  src/components/Header/index.jsx
  src/components/ProfileModal/ButtonBox/AdminButtonList/index.jsx
  src/components/PushNotification/CheckModal/index.jsx
  src/components/PushNotification/index.jsx
  src/pages/AdminPage/CustomerService/Report/ReportContent/MallangTalkModal/index.jsx
  src/pages/AdminPage/CustomerService/Report/ReportContent/index.jsx
  src/pages/AdminPage/Payment/Party/index.jsx
  src/pages/AdminPage/User/DriverRegistration/DriverDetail/AcceptButton/index.jsx
  src/pages/CommunityPage/ArticleDetail/ArticleBody/index.jsx
  src/pages/CommunityPage/ArticleDetail/ArticleComment/CommentItem/ReplyItem/index.jsx
  src/pages/CommunityPage/ArticleDetail/ArticleComment/CommentItem/index.jsx
  src/pages/DriverProfilePage/index.jsx
  src/pages/IntroPage/ServiceList/index.jsx
  src/pages/NewPartyPage/Course/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
  src/pages/NewPartyPage/Region/index.jsx
  src/pages/NewPartyPage/Reservation/index.jsx
  src/pages/NewPartyPage/index.jsx
  src/pages/TalkPage/TalkList/NewTalkButton/NewTalkModal/NewTalkInfo/index.jsx
  src/pages/TalkPage/TalkList/NewTalkButton/NewTalkModal/index.jsx
  src/pages/TalkPage/TalkList/NoTalkList/index.jsx
  src/pages/TalkPage/TalkList/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/ExitButton/ExitCheckModal/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/ExitButton/index.jsx
  src/pages/TalkPage/TalkRoom/TalkMenu/MenuHead/index.jsx
Labels: 🌏 Deploy

#162 파티 페이지 타인 비공개 처리 오류 수정
  src/pages/PartyPage/index.jsx
Labels: 🐛 Bug

#163 feat: 제안 코스 없는 드라이버에게 새로운 코스 만들어서 파티 제안
  src/components/CourseList/index.jsx
  src/components/PartyPlan/index.jsx
  src/pages/NewPartyPage/Course/index.jsx
  src/pages/NewPartyPage/Edit/PriceList/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
  src/pages/NewPartyPage/MemberAndDate/index.jsx
  src/pages/NewPartyPage/index.jsx
  src/pages/PartyPage/CourseDnD/index.jsx
Labels: ✨ Feature

#165 feat : 메인 페이지 검색창 삭제
  src/components/Header/index.jsx
  src/pages/CommunityPage/SearchBar/index.jsx
  src/pages/CommunityPage/index.jsx
  src/pages/CommunitySearchPage/index.jsx
  src/pages/SearchPlacePage/index.jsx
Labels: ✨ Feature

#167 여행자가 새로운 코스 생성 & 여행지 검색 창 제거
  src/components/CourseList/index.jsx
  src/components/Header/index.jsx
  src/components/PartyPlan/index.jsx
  src/hoc/Auth.jsx
  src/pages/CommunityPage/SearchBar/index.jsx
  src/pages/CommunityPage/index.jsx
  src/pages/CommunitySearchPage/index.jsx
  src/pages/NewPartyPage/Course/index.jsx
  src/pages/NewPartyPage/Edit/PriceList/index.jsx
  src/pages/NewPartyPage/Edit/index.jsx
  src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
  src/pages/NewPartyPage/MemberAndDate/index.jsx
  src/pages/NewPartyPage/index.jsx
  src/pages/PartyPage/CourseDnD/index.jsx
  src/pages/SearchPlacePage/index.jsx
  src/pages/TalkPage/TalkRoom/index.jsx
  src/pages/TalkPage/index.jsx
Labels: 🌏 Deploy

#169 푸시 알림 기능 개선
  public/firebase-messaging-sw.js
  src/api/notification.js
  src/components/PushNotification/index.jsx
  src/pages/NotifyPage/NotifyList/index.jsx
  src/redux/modules/userSlice.js
  src/utils/axios.js
Labels: ✨ Feature, 📬 API

#171 파티 말랑챗 버튼 스타일 수정
  src/assets/svg/go-party-chat.svg
  src/components/PartyIconBox/index.jsx
  src/pages/PartyPage/PartyMember/index.jsx
  src/pages/PartyPage/index.jsx
Labels: 🎨 Style

#172 새로운 파티 오류 수정
  src/pages/NewPartyPage/index.jsx
Labels: 🐛 Bug

#173 새로운 파티 만들기 오류 수정
  src/pages/NewPartyPage/index.jsx
Labels: 🐛 Bug

#174 새로운 파티 만들어 제안하기 로직 수정
  src/pages/DriverProfilePage/index.jsx
  src/pages/NewPartyPage/Driver/DriverProfile/index.jsx
  src/pages/NewPartyPage/Driver/index.jsx
  src/pages/NewPartyPage/index.jsx
Labels: ✨ Feature

#175 새로운 파티 만들어 제안하기 로직 수정
  src/pages/DriverProfilePage/index.jsx
  src/pages/NewPartyPage/Driver/DriverProfile/index.jsx
  src/pages/NewPartyPage/Driver/index.jsx
  src/pages/NewPartyPage/index.jsx
Labels: ✨ Feature

#178 feat : 서비스 이용약관 (일반회원 / 드라이버) 수정하기
  src/pages/PolicyPage/DriverService/index.jsx
  src/pages/PolicyPage/UserService/index.jsx
Labels: 📃 Docs
